In [1]:
import numpy as np

## numpy arrays

In [2]:
my_list = [20, 30, 40]

In [3]:
np.array(my_list)

array([20, 30, 40])

In [4]:
matrix_list = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [5]:
arr = np.array(matrix_list)
print(type(arr), "\n", arr)

<class 'numpy.ndarray'> 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


# arange

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros & ones

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [13]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# eye

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random


In [16]:
np.random.randn(5)

array([-2.10746144,  0.71938013, -0.43404851, -0.18859306, -0.53184157])

In [17]:
np.random.randn(4, 4)

array([[-2.7402265 , -0.82254188, -0.0393159 ,  0.67341163],
       [-0.36682537, -0.79760319,  0.46587404, -0.5896929 ],
       [ 1.64837341,  2.05963513, -1.37655587, -0.52203317],
       [-0.08954168, -0.30546985, -0.94294979,  0.59779582]])

In [18]:
np.random.randint(1, 10)

1

In [19]:
np.random.randint(1, 10, 5)

array([7, 4, 6, 5, 3])

In [20]:
np.random.randint(1, 10, (5, 5))

array([[5, 8, 7, 3, 5],
       [9, 2, 6, 7, 9],
       [9, 3, 2, 5, 5],
       [3, 8, 3, 2, 3],
       [5, 1, 6, 3, 9]])

# numpy array methods

In [21]:
my_numpy_array = np.arange(30)
reshaped_array = my_numpy_array.reshape(6, 5)
print(reshaped_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [22]:
my_random_array = np.random.randint(1, 100, 20)
my_random_array

array([48, 30, 34, 21, 62, 91,  6, 34, 31, 50, 70, 45, 57, 77, 63, 77, 82,
       51, 99, 75])

In [23]:
print("max element", my_random_array.max())
print("index of max element", my_random_array.argmax())

max element 99
index of max element 18


In [24]:
print("min element", my_random_array.min())
print("index of min element", my_random_array.argmin())

min element 6
index of min element 6


In [25]:
reshaped_array.shape


(6, 5)

# numpy operations

In [26]:
my_array = np.arange(0, 15)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
my_array[3:8] = 0

In [28]:
my_array

array([ 0,  1,  2,  0,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

In [29]:
other_array = np.arange(24)
other_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
slicing_piece_array = other_array[3:9]
slicing_piece_array

array([3, 4, 5, 6, 7, 8])

In [31]:
slicing_piece_array[:] = 700
slicing_piece_array

array([700, 700, 700, 700, 700, 700])

In [32]:
other_array

array([  0,   1,   2, 700, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [33]:
sample_array = np.arange(24)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
slicing_piece = sample_array[3: 9].copy()
slicing_piece

array([3, 4, 5, 6, 7, 8])

In [35]:
slicing_piece[:] = 600
slicing_piece

array([600, 600, 600, 600, 600, 600])

In [36]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# Matrix

In [37]:
matrix_list = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
my_matrix_array = np.array(matrix_list)
my_matrix_array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [38]:
my_matrix_array[0]

array([10, 20, 30])

In [39]:
print(my_matrix_array[1][1])
print(my_matrix_array[1,1])

50
50


In [40]:
my_matrix_array[1:, 2]

array([60, 90])

In [41]:
arr = np.arange(25)

In [42]:
new_matrix = arr.reshape(5, 5)
new_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
new_matrix[[0, 2, 4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [44]:
new_matrix[[4, 2, 0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [62]:
new_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
new_matrix[new_matrix[0, :] > 2]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# operations

In [45]:
my_list = np.random.randint(1, 100, 20)
my_list

array([24, 59, 97, 42, 67, 68, 49, 78, 33, 93, 34, 71, 83,  4,  1, 82, 85,
       20, 92,  4])

In [46]:
result_list = my_list > 50
result_list

array([False,  True,  True, False,  True,  True, False,  True, False,
        True, False,  True,  True, False, False,  True,  True, False,
        True, False])

In [47]:
my_list[result_list]

array([59, 97, 67, 68, 78, 93, 71, 83, 82, 85, 92])

In [48]:
my_list[my_list > 50]

array([59, 97, 67, 68, 78, 93, 71, 83, 82, 85, 92])

In [49]:
print(my_list + my_list)
print(my_list - my_list)
print(my_list * my_list)
print(my_list / my_list)

[ 48 118 194  84 134 136  98 156  66 186  68 142 166   8   2 164 170  40
 184   8]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 576 3481 9409 1764 4489 4624 2401 6084 1089 8649 1156 5041 6889   16
    1 6724 7225  400 8464   16]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [50]:
np.sqrt(my_list)

array([4.89897949, 7.68114575, 9.8488578 , 6.4807407 , 8.18535277,
       8.24621125, 7.        , 8.83176087, 5.74456265, 9.64365076,
       5.83095189, 8.42614977, 9.11043358, 2.        , 1.        ,
       9.05538514, 9.21954446, 4.47213595, 9.59166305, 2.        ])

In [51]:
np.max(my_list)

97

In [52]:
my_list2 = np.array([59, 60, 30,  9, 72, 51, 68, 54,  5, 99, 95, 52, 40, 70, 90, 22, 83, 62,  5, 31])


# My Note

In [53]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],
                          [[0, 1, 2, 3],[4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],[4, 5, 6, 7]]])
print("Dim :"+str(array_example.ndim))
print("Size :"+str(array_example.size))
print("Shape :"+str(array_example.shape))

Dim :3
Size :24
Shape :(3, 2, 4)


In [54]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [55]:
array_example.reshape(2, 4, 3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 0],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 0, 1],
        [2, 3, 4],
        [5, 6, 7]]])

In [56]:
list1 = [1, 3, 7]
list2 = [2, 4, 0]
arr1 = np.array(list1)
arr2 = np.array(list2)

print(list1 + list2)
print(arr1 + arr2)

[1, 3, 7, 2, 4, 0]
[3 7 7]


In [57]:
arr1 * arr2

array([ 2, 12,  0])

In [58]:
arr = np.array([1.1, 2.1, 3.1])

new_arr = arr.astype('str')

print(new_arr)
print(new_arr.dtype)

['1.1' '2.1' '3.1']
<U32
