In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr2 = np.eye(3) * 2
arr2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

# Matrix Product

In [4]:
arr * arr2

array([[ 2.,  0.,  0.],
       [ 0., 10.,  0.],
       [ 0.,  0., 18.]])

In [5]:
def product_of_matrix(arr, arr2):
    if arr.shape[1] != arr2.shape[0]:
            print("Shape error!!")
            
    if arr.shape[1] == arr2.shape[0]:
        pom = np.empty((arr.shape[0], arr2.shape[1]))
        for i in range(arr.shape[0]):
            for j in range(arr2.shape[1]):
                pom[i,j] = np.sum(arr[i,:]*arr2[:,j])
        
        return pom   
    

In [6]:
product_of_matrix(arr, arr2)

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [7]:
arr3 = np.array([1, 2, 3])
arr4 = arr3.reshape(3, 1)


In [8]:
product_of_matrix(arr2, arr4)

array([[2.],
       [4.],
       [6.]])

# Determinant

In [9]:
import math

In [10]:
def minor(arr, x, y):
    min_arr = np.delete(arr, x, axis=0)
    min_arr = np.delete(min_arr, y, axis=1)
    
    return min_arr   
    

In [11]:
minor(arr, 0, 2)

array([[4, 5],
       [7, 8]])

In [12]:
def determinant(arr, order):
    if order == 1:
        return arr[0]
    
    if order == 2:
        return arr[0,0]*arr[1,1] - arr[0,1]*arr[1,0]    
    else :
        det = 0
        for j in range(order):
            det += arr[0,j] * math.pow(-1,j) * determinant(minor(arr, 0, j), order-1)
        return det
        

In [14]:
arr = np.array([[1, 1, 2], [3, 1, 1], [1, 1, 4]])
arr

array([[1, 1, 2],
       [3, 1, 1],
       [1, 1, 4]])

In [15]:
arr5 = np.eye(4)*4
arr5

array([[4., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 4.]])

In [16]:
determinant(arr5, 4)

256.0